"""empty message

Revision ID: 2aa82572d243
Revises: da2377a08576
Create Date: 2020-01-18 03:07:43.111602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa82572d243'
down_revision = 'da2377a08576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('real_name', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'users', 'units', ['unit_id'], ['id'])
    op.drop_column('users', 'user_test')
    op.drop_column('users', 'user_test2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_test2', sa.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('user_test', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'real_name')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
