"""empty message

Revision ID: 4abdac1127fb
Revises: 908e94043433
Create Date: 2020-01-17 14:53:03.332870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abdac1127fb'
down_revision = '908e94043433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_test2', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_test2')
    # ### end Alembic commands ###
