"""empty message

Revision ID: 532a075572ea
Revises: 
Create Date: 2020-01-04 11:29:41.095066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532a075572ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'created')
    # ### end Alembic commands ###
