"""empty message

Revision ID: 798f9d17323b
Revises: 4abdac1127fb
Create Date: 2020-01-18 00:11:58.905509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798f9d17323b'
down_revision = '4abdac1127fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('who_create', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'who_create')
    # ### end Alembic commands ###
