"""empty message

Revision ID: 8b5c84e1166f
Revises: 2aa82572d243
Create Date: 2020-01-18 03:08:44.229158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5c84e1166f'
down_revision = '2aa82572d243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'units', ['unit_id'], ['id'])
    op.drop_column('users', 'user_test2')
    op.drop_column('users', 'user_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_test', sa.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('user_test2', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
