"""empty message

Revision ID: d271a69b9c2b
Revises: 8b5c84e1166f
Create Date: 2020-01-18 03:47:54.362770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd271a69b9c2b'
down_revision = '8b5c84e1166f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'units', ['unit_id'], ['id'])
    op.drop_column('users', 'user_test')
    op.drop_column('users', 'user_test2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_test2', sa.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('user_test', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
