"""empty message

Revision ID: da2377a08576
Revises: 798f9d17323b
Create Date: 2020-01-18 00:23:33.295499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2377a08576'
down_revision = '798f9d17323b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'unit_id')
    # ### end Alembic commands ###
